name: Deploy the Demo to GitHub Pages

on:
  workflow_dispatch:
    inputs:
      node-version:
        description: Node version
        required: true
        default: '16.x'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          yarn install
          yarn build:demo

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/demo
          branch: gh-pages
